
package signly;


import javafx.application.Platform;
import static signly.Classifier.run_classifier;


/**
* This class displays Main User Interface with the task selection for Training and Classifying 
* @author Monika Pusz 
* University of the West of England
* Student number: 16024757
* Course: Computer Science 
* @version 1.0
*/

public class TrainingSelection extends javax.swing.JFrame {

    // Declare the instance vaiables
    String letter = "";
    String image_path = "";

    
    public TrainingSelection() {
        initComponents();
        setTitle("Signly Letter Selection");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton40 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(955, 500));

        jPanel1.setBackground(new java.awt.Color(196, 224, 251));
        jPanel1.setMaximumSize(new java.awt.Dimension(955, 500));
        jPanel1.setMinimumSize(new java.awt.Dimension(955, 500));
        jPanel1.setPreferredSize(new java.awt.Dimension(955, 500));
        jPanel1.setLayout(null);

        jButton4.setBackground(new java.awt.Color(212, 175, 55));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/eixt small2.png"))); // NOI18N
        jButton4.setBorder(null);
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(850, 20, 90, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.PNG"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(290, 30, 330, 130);

        jButton6.setBackground(new java.awt.Color(212, 175, 55));
        jButton6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/home2.png"))); // NOI18N
        jButton6.setBorder(null);
        jButton6.setBorderPainted(false);
        jButton6.setContentAreaFilled(false);
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);
        jButton6.setBounds(770, 20, 60, 50);

        jButton7.setBackground(new java.awt.Color(255, 200, 153));
        jButton7.setFont(new java.awt.Font("Lucida Bright", 1, 24)); // NOI18N
        jButton7.setText("A");
        jButton7.setPreferredSize(new java.awt.Dimension(58, 52));
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });
        jPanel1.add(jButton7);
        jButton7.setBounds(120, 190, 58, 52);

        jButton8.setBackground(new java.awt.Color(255, 200, 153));
        jButton8.setFont(new java.awt.Font("Lucida Bright", 1, 24)); // NOI18N
        jButton8.setText("B");
        jButton8.setPreferredSize(new java.awt.Dimension(58, 52));
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton8MouseClicked(evt);
            }
        });
        jPanel1.add(jButton8);
        jButton8.setBounds(200, 190, 58, 52);

        jButton9.setBackground(new java.awt.Color(255, 200, 153));
        jButton9.setFont(new java.awt.Font("Lucida Bright", 1, 24)); // NOI18N
        jButton9.setText("C");
        jButton9.setPreferredSize(new java.awt.Dimension(58, 52));
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton9MouseClicked(evt);
            }
        });
        jPanel1.add(jButton9);
        jButton9.setBounds(280, 190, 58, 52);

        jButton10.setBackground(new java.awt.Color(255, 200, 153));
        jButton10.setFont(new java.awt.Font("Lucida Bright", 1, 24)); // NOI18N
        jButton10.setText("D");
        jButton10.setPreferredSize(new java.awt.Dimension(58, 52));
        jButton10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton10MouseClicked(evt);
            }
        });
        jPanel1.add(jButton10);
        jButton10.setBounds(360, 190, 58, 52);

        jButton11.setBackground(new java.awt.Color(255, 200, 153));
        jButton11.setFont(new java.awt.Font("Lucida Bright", 1, 24)); // NOI18N
        jButton11.setText("E");
        jButton11.setPreferredSize(new java.awt.Dimension(58, 52));
        jButton11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton11MouseClicked(evt);
            }
        });
        jPanel1.add(jButton11);
        jButton11.setBounds(440, 190, 58, 52);

        jButton12.setBackground(new java.awt.Color(255, 200, 153));
        jButton12.setFont(new java.awt.Font("Lucida Bright", 1, 24)); // NOI18N
        jButton12.setText("F");
        jButton12.setPreferredSize(new java.awt.Dimension(58, 52));
        jButton12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton12MouseClicked(evt);
            }
        });
        jPanel1.add(jButton12);
        jButton12.setBounds(520, 190, 58, 52);

        jButton13.setBackground(new java.awt.Color(255, 200, 153));
        jButton13.setFont(new java.awt.Font("Lucida Bright", 1, 24)); // NOI18N
        jButton13.setText("G");
        jButton13.setPreferredSize(new java.awt.Dimension(58, 52));
        jButton13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton13MouseClicked(evt);
            }
        });
        jPanel1.add(jButton13);
        jButton13.setBounds(600, 190, 58, 52);

        jButton14.setBackground(new java.awt.Color(255, 200, 153));
        jButton14.setFont(new java.awt.Font("Lucida Bright", 1, 24)); // NOI18N
        jButton14.setText("H");
        jButton14.setPreferredSize(new java.awt.Dimension(58, 52));
        jButton14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton14MouseClicked(evt);
            }
        });
        jPanel1.add(jButton14);
        jButton14.setBounds(680, 190, 58, 52);

        jButton15.setBackground(new java.awt.Color(255, 200, 153));
        jButton15.setFont(new java.awt.Font("Lucida Bright", 1, 24)); // NOI18N
        jButton15.setText("I");
        jButton15.setPreferredSize(new java.awt.Dimension(58, 52));
        jButton15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton15MouseClicked(evt);
            }
        });
        jPanel1.add(jButton15);
        jButton15.setBounds(760, 190, 58, 52);

        jButton16.setBackground(new java.awt.Color(255, 200, 153));
        jButton16.setFont(new java.awt.Font("Lucida Bright", 1, 24)); // NOI18N
        jButton16.setText("J");
        jButton16.setPreferredSize(new java.awt.Dimension(58, 52));
        jButton16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton16MouseClicked(evt);
            }
        });
        jPanel1.add(jButton16);
        jButton16.setBounds(120, 260, 58, 52);

        jButton17.setBackground(new java.awt.Color(255, 200, 153));
        jButton17.setFont(new java.awt.Font("Lucida Bright", 1, 24)); // NOI18N
        jButton17.setText("K");
        jButton17.setBorder(null);
        jButton17.setBorderPainted(false);
        jButton17.setPreferredSize(new java.awt.Dimension(58, 52));
        jButton17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton17MouseClicked(evt);
            }
        });
        jPanel1.add(jButton17);
        jButton17.setBounds(200, 260, 58, 52);

        jButton18.setBackground(new java.awt.Color(255, 200, 153));
        jButton18.setFont(new java.awt.Font("Lucida Bright", 1, 24)); // NOI18N
        jButton18.setText("L");
        jButton18.setPreferredSize(new java.awt.Dimension(58, 52));
        jButton18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton18MouseClicked(evt);
            }
        });
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton18);
        jButton18.setBounds(280, 260, 58, 52);

        jButton19.setBackground(new java.awt.Color(255, 200, 153));
        jButton19.setFont(new java.awt.Font("Lucida Bright", 1, 24)); // NOI18N
        jButton19.setText("M");
        jButton19.setPreferredSize(new java.awt.Dimension(58, 52));
        jButton19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton19MouseClicked(evt);
            }
        });
        jPanel1.add(jButton19);
        jButton19.setBounds(360, 260, 58, 52);

        jButton20.setBackground(new java.awt.Color(255, 200, 153));
        jButton20.setFont(new java.awt.Font("Lucida Bright", 1, 24)); // NOI18N
        jButton20.setText("N");
        jButton20.setPreferredSize(new java.awt.Dimension(58, 52));
        jButton20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton20MouseClicked(evt);
            }
        });
        jPanel1.add(jButton20);
        jButton20.setBounds(440, 260, 58, 52);

        jButton21.setBackground(new java.awt.Color(255, 200, 153));
        jButton21.setFont(new java.awt.Font("Lucida Bright", 1, 24)); // NOI18N
        jButton21.setText("O");
        jButton21.setPreferredSize(new java.awt.Dimension(58, 52));
        jButton21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton21MouseClicked(evt);
            }
        });
        jPanel1.add(jButton21);
        jButton21.setBounds(520, 260, 58, 52);

        jButton22.setBackground(new java.awt.Color(255, 200, 153));
        jButton22.setFont(new java.awt.Font("Lucida Bright", 1, 24)); // NOI18N
        jButton22.setText("P");
        jButton22.setPreferredSize(new java.awt.Dimension(58, 52));
        jButton22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton22MouseClicked(evt);
            }
        });
        jPanel1.add(jButton22);
        jButton22.setBounds(600, 260, 58, 52);

        jButton40.setBackground(new java.awt.Color(255, 200, 153));
        jButton40.setFont(new java.awt.Font("Lucida Bright", 1, 24)); // NOI18N
        jButton40.setText("Q");
        jButton40.setToolTipText("");
        jButton40.setPreferredSize(new java.awt.Dimension(58, 52));
        jButton40.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton40MouseClicked(evt);
            }
        });
        jPanel1.add(jButton40);
        jButton40.setBounds(680, 260, 58, 52);

        jButton23.setBackground(new java.awt.Color(255, 200, 153));
        jButton23.setFont(new java.awt.Font("Lucida Bright", 1, 24)); // NOI18N
        jButton23.setText("R");
        jButton23.setPreferredSize(new java.awt.Dimension(58, 52));
        jButton23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton23MouseClicked(evt);
            }
        });
        jPanel1.add(jButton23);
        jButton23.setBounds(760, 260, 58, 52);

        jButton24.setBackground(new java.awt.Color(255, 200, 153));
        jButton24.setFont(new java.awt.Font("Lucida Bright", 1, 24)); // NOI18N
        jButton24.setText("S");
        jButton24.setPreferredSize(new java.awt.Dimension(58, 52));
        jButton24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton24MouseClicked(evt);
            }
        });
        jPanel1.add(jButton24);
        jButton24.setBounds(120, 330, 58, 52);

        jButton25.setBackground(new java.awt.Color(255, 200, 153));
        jButton25.setFont(new java.awt.Font("Lucida Bright", 1, 24)); // NOI18N
        jButton25.setText("T");
        jButton25.setPreferredSize(new java.awt.Dimension(58, 52));
        jButton25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton25MouseClicked(evt);
            }
        });
        jPanel1.add(jButton25);
        jButton25.setBounds(200, 330, 58, 52);

        jButton31.setBackground(new java.awt.Color(255, 200, 153));
        jButton31.setFont(new java.awt.Font("Lucida Bright", 1, 24)); // NOI18N
        jButton31.setText("Z");
        jButton31.setToolTipText("");
        jButton31.setPreferredSize(new java.awt.Dimension(58, 52));
        jButton31.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton31MouseClicked(evt);
            }
        });
        jPanel1.add(jButton31);
        jButton31.setBounds(680, 330, 58, 52);

        jButton28.setBackground(new java.awt.Color(255, 200, 153));
        jButton28.setFont(new java.awt.Font("Lucida Bright", 1, 24)); // NOI18N
        jButton28.setText("Y");
        jButton28.setToolTipText("");
        jButton28.setPreferredSize(new java.awt.Dimension(58, 52));
        jButton28.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton28MouseClicked(evt);
            }
        });
        jPanel1.add(jButton28);
        jButton28.setBounds(600, 330, 58, 52);

        jButton27.setBackground(new java.awt.Color(255, 200, 153));
        jButton27.setFont(new java.awt.Font("Lucida Bright", 1, 24)); // NOI18N
        jButton27.setText("X");
        jButton27.setToolTipText("");
        jButton27.setPreferredSize(new java.awt.Dimension(58, 52));
        jButton27.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton27MouseClicked(evt);
            }
        });
        jPanel1.add(jButton27);
        jButton27.setBounds(520, 330, 58, 52);

        jButton26.setBackground(new java.awt.Color(255, 200, 153));
        jButton26.setFont(new java.awt.Font("Lucida Bright", 1, 24)); // NOI18N
        jButton26.setText("W");
        jButton26.setToolTipText("");
        jButton26.setPreferredSize(new java.awt.Dimension(58, 52));
        jButton26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton26MouseClicked(evt);
            }
        });
        jPanel1.add(jButton26);
        jButton26.setBounds(440, 330, 58, 52);

        jButton30.setBackground(new java.awt.Color(255, 200, 153));
        jButton30.setFont(new java.awt.Font("Lucida Bright", 1, 24)); // NOI18N
        jButton30.setText("U");
        jButton30.setPreferredSize(new java.awt.Dimension(58, 52));
        jButton30.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton30MouseClicked(evt);
            }
        });
        jPanel1.add(jButton30);
        jButton30.setBounds(280, 330, 58, 52);

        jButton29.setBackground(new java.awt.Color(255, 200, 153));
        jButton29.setFont(new java.awt.Font("Lucida Bright", 1, 24)); // NOI18N
        jButton29.setText("V");
        jButton29.setPreferredSize(new java.awt.Dimension(58, 52));
        jButton29.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton29MouseClicked(evt);
            }
        });
        jPanel1.add(jButton29);
        jButton29.setBounds(360, 330, 58, 52);

        jButton32.setBackground(new java.awt.Color(212, 175, 55));
        jButton32.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/back.png"))); // NOI18N
        jButton32.setBorder(null);
        jButton32.setBorderPainted(false);
        jButton32.setContentAreaFilled(false);
        jButton32.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton32MouseClicked(evt);
            }
        });
        jButton32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton32ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton32);
        jButton32.setBounds(20, 20, 60, 50);

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator2);
        jSeparator2.setBounds(840, 30, 10, 40);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pexels-photo-1242348.jpeg"))); // NOI18N
        jLabel6.setText("jLabel6");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(0, 0, 960, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 955, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
  
        /**
        * Exit Button 
        * Closes the program
        */ 
        
        Platform.exit();
        System.exit(0);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
       
        /**
        * Home Button 
        * Displays Home window to user, closing current displayed window 
        */
        
        this.setVisible(false);
        new SignlyMain().setVisible(true);

        
    }//GEN-LAST:event_jButton6MouseClicked

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
        // Button A
        letter = "A";
        image_path = "/img/A.png";
        this.setVisible(false);

        Training.main(null, letter, image_path);
    }//GEN-LAST:event_jButton7MouseClicked

    private void jButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseClicked
        // Button B
        letter = "B";
        image_path = "/img/B.png";
        this.setVisible(false);

        Training.main(null, letter, image_path);
    }//GEN-LAST:event_jButton8MouseClicked

    private void jButton9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseClicked
        // Button C
        letter = "C";
        image_path = "/img/C.png";
        this.setVisible(false);

        Training.main(null, letter, image_path);
    }//GEN-LAST:event_jButton9MouseClicked

    private void jButton10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton10MouseClicked
        // Button D
        letter = "D";
        image_path = "/img/D.png";
        this.setVisible(false);

        Training.main(null, letter, image_path);
    }//GEN-LAST:event_jButton10MouseClicked

    private void jButton11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton11MouseClicked
        // Button E
        letter = "E";
        image_path = "/img/E.png";
        this.setVisible(false);

        Training.main(null, letter, image_path);
    }//GEN-LAST:event_jButton11MouseClicked

    private void jButton12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton12MouseClicked
        // Button F
        letter = "F";
        image_path = "/img/F.png";
        this.setVisible(false);

        Training.main(null, letter, image_path);
    }//GEN-LAST:event_jButton12MouseClicked

    private void jButton13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton13MouseClicked
        // Button G
        letter = "G";
        image_path = "/img/G.png";
        this.setVisible(false);

        Training.main(null, letter, image_path);
    }//GEN-LAST:event_jButton13MouseClicked

    private void jButton14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton14MouseClicked
        // Button H
        letter = "H";
        image_path = "/img/H.png";
        this.setVisible(false);

        Training.main(null, letter, image_path);
    }//GEN-LAST:event_jButton14MouseClicked

    private void jButton15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton15MouseClicked
        // Button I
        letter = "I";
        image_path = "/img/I.png";
        this.setVisible(false);

        Training.main(null, letter, image_path);
    }//GEN-LAST:event_jButton15MouseClicked

    private void jButton16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton16MouseClicked
        // Button J
        letter = "J";
        image_path = "/img/J.png";
        this.setVisible(false);

        Training.main(null, letter, image_path);
    }//GEN-LAST:event_jButton16MouseClicked

    private void jButton17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton17MouseClicked
        // Button K
        letter = "K";
        image_path = "/img/K.png";
        this.setVisible(false);

        Training.main(null, letter, image_path);
    }//GEN-LAST:event_jButton17MouseClicked

    private void jButton18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton18MouseClicked
        // Button L
        letter = "L";
        image_path = "/img/L.png";
        this.setVisible(false);

        Training.main(null, letter, image_path);
    }//GEN-LAST:event_jButton18MouseClicked

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton19MouseClicked
        // Button M
        letter = "M";
        image_path = "/img/M.png";
        this.setVisible(false);

        Training.main(null, letter, image_path);
    }//GEN-LAST:event_jButton19MouseClicked

    private void jButton20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton20MouseClicked
        // Button N
        letter = "N";
        image_path = "/img/N.png";
        this.setVisible(false);

        Training.main(null, letter, image_path);
    }//GEN-LAST:event_jButton20MouseClicked

    private void jButton21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton21MouseClicked
        // Button O
        letter = "O";
        image_path = "/img/O.png";
        this.setVisible(false);

        Training.main(null, letter, image_path);
    }//GEN-LAST:event_jButton21MouseClicked

    private void jButton22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton22MouseClicked
        // Button P
        letter = "P";
        image_path = "/img/P.png";
        this.setVisible(false);

        Training.main(null, letter, image_path);
    }//GEN-LAST:event_jButton22MouseClicked

    private void jButton40MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton40MouseClicked
        // Button Q
        letter = "Q";
        image_path = "/img/Q.png";
        this.setVisible(false);

        Training.main(null, letter, image_path);
    }//GEN-LAST:event_jButton40MouseClicked

    private void jButton23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton23MouseClicked
        // Button R
        letter = "R";
        image_path = "/img/R.png";
        this.setVisible(false);

        Training.main(null, letter, image_path);
    }//GEN-LAST:event_jButton23MouseClicked

    private void jButton24MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton24MouseClicked
        // Button S
        letter = "S";
        image_path = "/img/S.png";
        this.setVisible(false);

        Training.main(null, letter, image_path);
    }//GEN-LAST:event_jButton24MouseClicked

    private void jButton25MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton25MouseClicked
        // Button T
        letter = "T";
        image_path = "/img/T.png";
        this.setVisible(false);

        Training.main(null, letter, image_path);
    }//GEN-LAST:event_jButton25MouseClicked

    private void jButton31MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton31MouseClicked
        // Button Z
        letter = "Z";
        image_path = "/img/Z.png";
        this.setVisible(false);

        Training.main(null, letter, image_path);
    }//GEN-LAST:event_jButton31MouseClicked

    private void jButton28MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton28MouseClicked
        // Button Y
        letter = "Y";
        image_path = "/img/Y.png";
        this.setVisible(false);

        Training.main(null, letter, image_path);
    }//GEN-LAST:event_jButton28MouseClicked

    private void jButton27MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton27MouseClicked
        // Button X
        letter = "X";
        image_path = "/img/X.png";
        this.setVisible(false);

        Training.main(null, letter, image_path);
    }//GEN-LAST:event_jButton27MouseClicked

    private void jButton26MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton26MouseClicked
        // Button W
        letter = "W";
        image_path = "/img/W.png";
        this.setVisible(false);

        Training.main(null, letter, image_path);
    }//GEN-LAST:event_jButton26MouseClicked

    private void jButton29MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton29MouseClicked
        // Button V
        letter = "V";
        image_path = "/img/V.png";
        this.setVisible(false);

        Training.main(null, letter, image_path);
    }//GEN-LAST:event_jButton29MouseClicked

    private void jButton30MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton30MouseClicked
        // Button U
        letter = "U";
        image_path = "/img/U.png";
        this.setVisible(false);

        Training.main(null, letter, image_path);
    }//GEN-LAST:event_jButton30MouseClicked

    private void jButton32MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton32MouseClicked
        /**
        * Back Button 
        * Returns to the previous window 
        */
        
        this.setVisible(false);
        SignlyMain.main(null);
    }//GEN-LAST:event_jButton32MouseClicked

    private void jButton32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton32ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton32ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrainingSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrainingSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrainingSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrainingSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrainingSelection().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton40;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
